# Generated by Django 3.1 on 2021-12-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, default='static/flavio.jpeg', upload_to='static', verbose_name='Picture'),
        ),
    ]
